#####################------------------------------------------------------------------------####################
### ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: ###
####  Cloud-Print-Output [  Hide-Iframe  --- Assign  ] ###
### ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: ###
###-------------home----------------###
document.getElementById('hide_show_output_iframe').innerHTML ='  <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="  http://www.w3schools.com/html/tryit.asp?filename=tryhtml_default "  ></iframe>  '
###-----------[  introduction   ]--------------###
#document.getElementById('hide_show_output_iframe').innerHTML  =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_intro_inner_html " ></iframe>  ' 
document.getElementById('hide_show_output_iframe1').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_intro_lightbulb "  ></iframe>  '
document.getElementById('hide_show_output_iframe2').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_intro_style "      ></iframe>  '
document.getElementById('hide_show_output_iframe3').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_intro_hide "       ></iframe>  '
document.getElementById('hide_show_output_iframe4').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_intro_show "       ></iframe>  '
document.getElementById('hide_show_output_iframe5').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_myfirst "          ></iframe>  '
###-----------[ where to  ]--------------###
document.getElementById('hide_show_output_iframe6').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_whereto "         ></iframe>  '
document.getElementById('hide_show_output_iframe7').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_whereto_head "    ></iframe>  '
document.getElementById('hide_show_output_iframe8').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_whereto_body "    ></iframe>  '
document.getElementById('hide_show_output_iframe9').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_whereto_external "></iframe>  '
document.getElementById('hide_show_output_iframe10').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_whereto_url "     ></iframe>  '
document.getElementById('hide_show_output_iframe11').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_whereto_url_relative " ></iframe>  '
document.getElementById('hide_show_output_iframe12').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_whereto_external "     ></iframe>  '
###-----------[  output   ]--------------###
document.getElementById('hide_show_output_iframe13').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_output_alert "        ></iframe>  '
document.getElementById('hide_show_output_iframe14').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_output_write "        ></iframe>  '
document.getElementById('hide_show_output_iframe15').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_output_write_over "   ></iframe>  '
document.getElementById('hide_show_output_iframe16').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_output_dom "          ></iframe>  '
document.getElementById('hide_show_output_iframe17').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_output_console "      ></iframe>  '
###-----------[  syntaxis   ]--------------###
document.getElementById('hide_show_output_iframe18').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_syntax_statements "    ></iframe>  '
document.getElementById('hide_show_output_iframe19').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_syntax_numbers "       ></iframe>  '
document.getElementById('hide_show_output_iframe20').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_syntax_strings "       ></iframe>  '
document.getElementById('hide_show_output_iframe21').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_syntax_variables "     ></iframe>  '
document.getElementById('hide_show_output_iframe22').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_syntax_assign "        ></iframe>  '
document.getElementById('hide_show_output_iframe23').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_syntax_operators "     ></iframe>  '
document.getElementById('hide_show_output_iframe24').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_syntax_expressions "   ></iframe>  '
document.getElementById('hide_show_output_iframe25').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_syntax_expressions_variables "  ></iframe>  '
document.getElementById('hide_show_output_iframe26').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_syntax_expressions_strings "    ></iframe>  '
document.getElementById('hide_show_output_iframe27').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_syntax_keywords "    ></iframe>  '
document.getElementById('hide_show_output_iframe28').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_syntax_comments "    ></iframe>  '
document.getElementById('hide_show_output_iframe29').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_syntax_case "        ></iframe>  '
###-----------[  stantence   ]--------------###
document.getElementById('hide_show_output_iframe30').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_statement "    ></iframe>  '
document.getElementById('hide_show_output_iframe31').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_statements "    ></iframe>  '
document.getElementById('hide_show_output_iframe32').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_statements_semicolon1 "    ></iframe>  '
document.getElementById('hide_show_output_iframe33').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_statements_semicolon2 "    ></iframe>  '
document.getElementById('hide_show_output_iframe34').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_statements_linebreak "    ></iframe>  '
document.getElementById('hide_show_output_iframe35').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_statements_blocks "    ></iframe>  '
###-----------[ comments   ]--------------###
document.getElementById('hide_show_output_iframe36').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_comments1 "    ></iframe>  '
document.getElementById('hide_show_output_iframe37').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_comments2 "    ></iframe>  '
document.getElementById('hide_show_output_iframe38').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_comments3 "    ></iframe>  '
document.getElementById('hide_show_output_iframe39').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_comments4 "    ></iframe>  '
document.getElementById('hide_show_output_iframe40').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_comments5 "    ></iframe>  '


###-----------[ comments   ]--------------###
document.getElementById('hide_show_output_iframe42').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_comments1 "    ></iframe>    '
document.getElementById('hide_show_output_iframe43').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_comments2 "    ></iframe>    '
document.getElementById('hide_show_output_iframe44').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_comments3 "    ></iframe>    '
document.getElementById('hide_show_output_iframe45').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_comments4 "    ></iframe>    '
document.getElementById('hide_show_output_iframe46').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_comments5 "    ></iframe>    '
###-----------[  variable   ]--------------###
document.getElementById('hide_show_output_iframe47').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_variables "    ></iframe>    '
document.getElementById('hide_show_output_iframe48').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_variables_total "    ></iframe>    '
document.getElementById('hide_show_output_iframe49').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_variables_types "    ></iframe>    '
document.getElementById('hide_show_output_iframe50').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_variables_create "    ></iframe>    '
document.getElementById('hide_show_output_iframe51').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_variables_multi "    ></iframe>    '
document.getElementById('hide_show_output_iframe52').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_variables_multiline "    ></iframe>    '
document.getElementById('hide_show_output_iframe53').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_variables_undefined "    ></iframe>    '
document.getElementById('hide_show_output_iframe54').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_variables_redefine "    ></iframe>    '
document.getElementById('hide_show_output_iframe55').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_variables_add_numbers "    ></iframe>    '
document.getElementById('hide_show_output_iframe56').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_variables_add_strings "    ></iframe>    '
document.getElementById('hide_show_output_iframe57').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_variables_add_string_number "    ></iframe>    '
document.getElementById('hide_show_output_iframe58').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_variables_add_number_string "    ></iframe>    '
###-----------[  Operator   ]--------------###
document.getElementById('hide_show_output_iframe59').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_oper "    ></iframe>    '
document.getElementById('hide_show_output_iframe60').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_oper_equal "    ></iframe>    '
document.getElementById('hide_show_output_iframe61').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_oper_add "    ></iframe>    '
document.getElementById('hide_show_output_iframe62').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_oper_mult "    ></iframe>    '
document.getElementById('hide_show_output_iframe63').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_oper_plusequ "    ></iframe>    '
document.getElementById('hide_show_output_iframe64').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_oper_concate "    ></iframe>    '
document.getElementById('hide_show_output_iframe65').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_oper_concat4 "    ></iframe>    '
document.getElementById('hide_show_output_iframe66').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_oper_concat5 "    ></iframe>    '
###-----------[ aritment    ]--------------###
document.getElementById('hide_show_output_iframe67').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_arithmetic_operation "    ></iframe>    '
document.getElementById('hide_show_output_iframe68').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_arithmetic_variables "    ></iframe>    '
document.getElementById('hide_show_output_iframe69').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_arithmetic_expressions "    ></iframe>    '
document.getElementById('hide_show_output_iframe70').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_oper_add "    ></iframe>    '
document.getElementById('hide_show_output_iframe71').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_oper_sub "    ></iframe>    '
document.getElementById('hide_show_output_iframe72').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_oper_mult "    ></iframe>    '
document.getElementById('hide_show_output_iframe73').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_oper_div "    ></iframe>    '
document.getElementById('hide_show_output_iframe74').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_oper_mod "    ></iframe>    '
document.getElementById('hide_show_output_iframe75').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_oper_increment "    ></iframe>    '
document.getElementById('hide_show_output_iframe76').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_oper_decrement "    ></iframe>    '
document.getElementById('hide_show_output_iframe77').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_arithmetic_precedence1 "    ></iframe>    '
document.getElementById('hide_show_output_iframe78').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_arithmetic_precedence2 "    ></iframe>    '
document.getElementById('hide_show_output_iframe79').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_arithmetic_precedence3 "    ></iframe>    '
###-----------[  assign   ]--------------###
document.getElementById('hide_show_output_iframe80').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_assign_plusequal "    ></iframe>    '
document.getElementById('hide_show_output_iframe81').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_assign_minequal "    ></iframe>    '
document.getElementById('hide_show_output_iframe82').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_assign_minequal "    ></iframe>    ' 
document.getElementById('hide_show_output_iframe83').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_assign_multequal "    ></iframe>    ' 
document.getElementById('hide_show_output_iframe84').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_assign_divequal "    ></iframe>    ' 
document.getElementById('hide_show_output_iframe85').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_assign_modequal "    ></iframe>    ' 
###-----------[  data-types   ]--------------###
document.getElementById('hide_show_output_iframe86').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_datatypes_addstring "    ></iframe>    ' 
document.getElementById('hide_show_output_iframe87').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_datatypes_addstring2 "    ></iframe>    ' 
document.getElementById('hide_show_output_iframe88').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_datatypes_addstrings_1 "    ></iframe>    ' 
document.getElementById('hide_show_output_iframe89').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_datatypes_addstrings_2 "    ></iframe>    ' 
document.getElementById('hide_show_output_iframe90').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_datatypes_string "    ></iframe>    ' 
document.getElementById('hide_show_output_iframe91').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_datatypes_numbers "    ></iframe>    ' 
document.getElementById('hide_show_output_iframe92').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_datatypes_array "    ></iframe>    ' 
document.getElementById('hide_show_output_iframe93').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_datatypes_object "    ></iframe>    ' 
document.getElementById('hide_show_output_iframe94').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_datatypes_typeof "    ></iframe>    ' 
document.getElementById('hide_show_output_iframe95').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_datatypes_undefined "    ></iframe>    ' 
document.getElementById('hide_show_output_iframe96').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_datatypes_undefined_2 "    ></iframe>    ' 
document.getElementById('hide_show_output_iframe97').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_datatypes_empty "    ></iframe>    ' 
document.getElementById('hide_show_output_iframe98').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_datatypes_null "    ></iframe>    ' 
document.getElementById('hide_show_output_iframe99').innerHTML =  ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_datatypes_undefined_1 "    ></iframe>    ' 
document.getElementById('hide_show_output_iframe100').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_typeof_undefined_3 "    ></iframe>    '
###-----------[  functions   ]--------------###
document.getElementById('hide_show_output_iframe101').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_functions "    ></iframe>    '
document.getElementById('hide_show_output_iframe102').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_function_return "    ></iframe>    '
document.getElementById('hide_show_output_iframe103').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_farenheit_to_celsius "    ></iframe>    '
document.getElementById('hide_show_output_iframe104').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_farenheit_to_celsius_2 "    ></iframe>    '
document.getElementById('hide_show_output_iframe105').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_function_variable "    ></iframe>    '
###-----------[  objects   ]--------------###
document.getElementById('hide_show_output_iframe106').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_objects_variable "    ></iframe>    '
document.getElementById('hide_show_output_iframe107').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_objects_object "    ></iframe>    '
document.getElementById('hide_show_output_iframe108').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_objects_create_1 "    ></iframe>    '
document.getElementById('hide_show_output_iframe109').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_objects_create_2 "    ></iframe>    '
document.getElementById('hide_show_output_iframe110').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_objects_properties_1 "    ></iframe>    '
document.getElementById('hide_show_output_iframe111').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_objects_properties_2 "    ></iframe>    '
document.getElementById('hide_show_output_iframe112').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_objects_method "    ></iframe>    '
document.getElementById('hide_show_output_iframe113').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src="http://www.w3schools.com/js/tryit.asp?filename=tryjs_objects_function "    ></iframe>    '
###-----------[     ]--------------###
document.getElementById('hide_show_output_iframe114').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe115').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe116').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe117').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe118').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe119').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe120').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe121').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe122').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe123').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe124').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe125').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe126').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe127').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe128').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe129').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe130').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe131').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe132').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe133').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe134').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe135').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe136').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe137').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe138').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe139').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe130').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe141').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe142').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe143').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe144').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe145').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe146').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe147').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe148').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe149').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe150').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe151').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe152').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe153').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe154').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe155').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe156').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe157').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe158').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe159').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
document.getElementById('hide_show_output_iframe160').innerHTML = ' <iframe height="500px" width="850px" style="border:1px aqua solid;"  src=" "    ></iframe>    '
